version: '3'

services:
  dev:
    build:
      context: ./app
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/portfolio
    environment:
      NODE_ENV: development

  production:
    build:
      context: ./app
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    command: /bin/bash -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: nginx
    volumes: 
      - ./logs/nginx/:/var/log/nginx:rw
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs/:/etc/letsencrypt
      - ./data/:data/letsencrypt
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - production

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/data/letsencrypt
    entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"'
    depends_on:
      - nginx
