services:
  dev:
    build:
      context: ${APP_CONTEXT}
      target: ${DEV_TARGET}
    ports:
      - "${APP_PORT}"
    volumes:
      - ${DEV_VOLUME}
    environment:
      NODE_ENV: ${DEV_NODE_ENV}
    depends_on:
      - nginx

  production:
    build:
      context: ${APP_CONTEXT}
      target: ${PROD_TARGET}
    ports:
      - "${APP_PORT}"
    container_name: ${PROD_CONTAINER_NAME}
    environment:
      NODE_ENV: ${PROD_NODE_ENV}

  nginx:
    build:
      context: ${NGINX_CONTEXT}
      target: ${NGINX_TARGET}
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    volumes:
      - ${NGINX_LOG_VOLUME}
      - ${NGINX_INCLUDES_VOLUME}
      - ${NGINX_CONF_VOLUME}
      - ${CERTS_VOLUME}
      - ${DATA_VOLUME}
      - ${NGINX_TEMPLATES_VOLUME}


  certbot:
    build:
      context: ${NGINX_CONTEXT}
      target: ${CERTBOT_TARGET}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    volumes:
      - ${NGINX_CONF_VOLUME}
      - ${CERTS_VOLUME}
      - ${DATA_VOLUME}
