version: '3'

services:
  dev:
    build:
      context: ./app
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/portfolio
    environment:
      NODE_ENV: development

  production:
    build:
      context: ./app
      target: production
    ports:
      - "3000:3000"
    container_name: production
    environment:
      NODE_ENV: production

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    volumes:
      - ./logs/nginx/:/var/log/nginx:rw
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs/:/etc/letsencrypt
      - ./data/:/data/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
