receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: ${env:OTEL_PROMETHEUS_EXPORTER_ENDPOINT}
    const_labels:
      label1: ${env:OTEL_CONST_LABEL}

  logging:

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :${env:OTEL_PPROF_PORT}
  zpages:
    endpoint: :${env:OTEL_ZPAGES_PORT}

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
