server:
  http_listen_port: ${PROMTAIL_HTTP_PORT}
  grpc_listen_port: ${PROMTAIL_GRPC_PORT}

positions:
  filename: ${PROMTAIL_POSITIONS_FILE}

clients:
  - url: ${PRONTAIL_LOKI_CLIENT_URL}
    tenant_id: ${LOKI_TENANT_ID}
    basic_auth:
      username: ${LOKI_AUTH_USERNAME}
      password: ${LOKI_AUTH_PASSWORD}

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          environment: ${ENV_TYPE}

  # Docker container logs with enhanced labeling and parsing
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Extract container name
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"

      # Extract service name from container labels
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"

      # Add environment label
      - source_labels: []
        target_label: "environment"
        replacement: "${ENV_TYPE}"

    # General Docker log processing pipeline
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time

      - timestamp:
          source: time
          format: RFC3339Nano

      - labels:
          stream:

      # Add dynamic pipeline stages based on service type
      - match:
          selector: '{service="backend"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
                  path: path
                  method: method
                  status_code: status_code
                  duration_ms: duration_ms
            - labels:
                level:
                method:
                path:
                status_code:

      - match:
          selector: '{service="frontend"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
                  component: component
            - labels:
                level:
                component:

      - match:
          selector: '{service="postgres"}'
          stages:
            - regex:
                expression: "(?P<postgres_log_level>INFO|NOTICE|WARNING|ERROR|LOG|FATAL|PANIC)"
            - regex:
                expression: "duration: (?P<query_duration_ms>[0-9.]+) ms"
            - labels:
                postgres_log_level:
                query_duration:

      # - match:
      #     selector: '{service="nginx"}'
      #     stages:
      #       - regex:
      #           expression: '(?P<status_code>\d{3}) (?P<body_bytes_sent>\d+) (?P<request_time>[0-9.]+)'
      #       - labels:
      #           status_code:
      #           request_time:
