name: portfolio-infra
description: Personal portfolio infrastructure (Traefik reverse proxy, apps, Postgres) managed with Pulumi YAML and Docker. TLS per stack; no extra runtimes on the host.
runtime: yaml

config:
  {
    "pulumi:tags": { value: { "pulumi:template": yaml } },
    "pulumi:autonaming": { value: { pattern: "${name}-${project}-${stack}" } },

    "POSTGRES_USER": { type: "string", secret: true },
    "POSTGRES_PASSWORD": { type: "string", secret: true },
    "POSTGRES_DB": { type: "string", secret: true },
    "POSTGRES_PORT": { type: "string", default: "5432" },
    "POSTGRES_VOLUME_NAME":
      { type: "string", default: "portfolio_postgres_data" },

    "HTTP_PORT": { type: "string", default: "80" },
    "HTTPS_PORT": { type: "string", default: "443" },

    "DOMAIN_NAME": { type: "string", default: "localhost" },

    "ADMIN_EMAIL": { type: "string", secret: true },
    "ADMIN_PASSWORD": { type: "string", secret: true },
    "AUTH_SECRET": { type: "string", secret: true },
    "AUTH_TRUST_HOST": { type: "string", default: "true" },
    "AUTH_BASE_PATH": { type: "string", secret: true },

    "PORTFOLIO_IMAGE_NAME": { type: "string", default: "portfolio_image" },
    "APP_PORT": { type: "string", default: "3000" },
    "PORTFOLIO_BUILD_CONTEXT": { type: "string", default: "./app" },
    "PORTFOLIO_WORKDIR_PATH": { type: "string", default: "/portfolio/app" },
    "PORTFOLIO_IMAGE_BUILD_NAME":
      { type: "string", default: "portfolio_built_image" },
    "PORTFOLIO_BUILD_PHASE_TARGET": { type: "string", default: "development" },
    "ENABLE_TLS": { type: "boolean", default: false },
    "ROUTER_ENTRYPOINT": { type: "string", default: "web" },
    "PROMETHEUS_INTERNAL_PORT": { type: "string", default: "9090" },
    "PROMETHEUS_EXTERNAL_PORT": { type: "string", default: "9090" },
    "PROMETHEUS_CONFIG_FILE_DIR":
      { type: "string", default: "observation/prometheus/prometheus.yaml" },
    "PROMETHEUS_SCRAPE_INTERVAL": { type: "string", default: "15s" },
    "PROMETHEUS_EVALUATION_INTERVAL": { type: "string", default: "15s" },
    "NODE_EXPORTER_INTERNAL_PORT": { type: "string", default: "9100" },
    "NODE_EXPORTER_EXTERNAL_PORT": { type: "string", default: "9100" },
    "CADVISOR_INTERNAL_PORT": { type: "string", default: "8080" },
    "CADVISOR_EXTERNAL_PORT": { type: "string", default: "8080" },
    "LOKI_INTERNAL_PORT": { type: "string", default: "3100" },
    "LOKI_EXTERNAL_PORT": { type: "string", default: "3100" },
    "LOKI_CONFIG_FILE_DIR":
      { type: "string", default: "observation/loki/loki.yaml" },
    "PROMTAIL_CONFIG_FILE_DIR":
      { type: "string", default: "observation/promtail/promtail.yaml" },
    "GRAFANA_INTERNAL_PORT": { type: "string", default: "3001" },
    "GRAFANA_EXTERNAL_PORT": { type: "string", default: "3001" },
    "GRAFANA_CONFIG_DIR": { type: "string", default: "observation/grafana" },
    "GRAFANA_ADMIN_USER": { type: "string", secret: true },
    "GRAFANA_ADMIN_PASSWORD": { type: "string", secret: true },
    "ALERTMANAGER_CONFIG_FILE_DIR":
      { type: "string", default: "observation/alertmanager/alertmanager.yaml" },
    "ALERTMANAGER_INTERNAL_PORT": { type: "string", default: "9093" },
    "ALERTMANAGER_EXTERNAL_PORT": { type: "string", default: "9093" },
    "ALERTMANAGER_RESOLVE_TIMEOUT": { type: "string", default: "5m" },
    "ALERTMANAGER_GROUP_WAIT": { type: "string", default: "30s" },
    "ALERTMANAGER_GROUP_INTERVAL": { type: "string", default: "5m" },
    "ALERTMANAGER_REPEAT_INTERVAL": { type: "string", default: "12h" },
    "ALERTMANAGER_EMAIL_TO": { type: "string", secret: true },
    "ALERTMANAGER_EMAIL_FROM": { type: "string", secret: true },
    "ALERTMANAGER_SMTP_HOST": { type: "string", secret: true },
    "ALERTMANAGER_SMTP_PORT": { type: "string", secret: true },
    "ALERTMANAGER_SMTP_USERNAME": { type: "string", secret: true },
    "ALERTMANAGER_SMTP_PASSWORD": { type: "string", secret: true },
    "LOKI_AUTH_ENABLED": { type: "boolean", default: false },
    "LOKI_GRPC_PORT": { type: "string", default: "9096" },
    "LOKI_INSTANCE_ADDRESS": { type: "string", default: "127.0.0.1" },
    "LOKI_PATH_PREFIX": { type: "string", default: "/tmp/loki" },
    "LOKI_CHUNKS_DIR": { type: "string", default: "/tmp/loki/chunks" },
    "LOKI_RULES_DIR": { type: "string", default: "/tmp/loki/rules" },
    "LOKI_REPLICATION_FACTOR": { type: "string", default: "1" },
    "LOKI_KVSTORE": { type: "string", default: "inmemory" },
    "PROMTAIL_HTTP_PORT": { type: "string", default: "9080" },
    "PROMTAIL_GRPC_PORT": { type: "string", default: "0" },
    "PROMTAIL_POSITIONS_FILE":
      { type: "string", default: "/tmp/positions.yaml" },
    "LOKI_TENANT_ID": { type: "string", default: "1" },
    "LOKI_AUTH_USERNAME": { type: "string", secret: true },
    "LOKI_AUTH_PASSWORD": { type: "string", secret: true },
    "ENV_TYPE": { type: "string", default: "development" },
    "POSTGRES_EXPORTER_INTERNAL_PORT": { type: "string", default: "9187" },
    "POSTGRES_EXPORTER_EXTERNAL_PORT": { type: "string", default: "9187" },
    "NGINX_EXPORTER_INTERNAL_PORT": { type: "string", default: "9113" },
    "NGINX_EXPORTER_EXTERNAL_PORT": { type: "string", default: "9113" },
    "NGINX_STUB_STATUS_PORT": { type: "string", default: "8080" },
    "NGINX_NETWORK_ALIAS": { type: "string", default: "nginx" },
    "TRAEFIK_METRICS_PORT": { type: "string", default: "4318" },
  }

variables:
  {
    POSTGRES_USER: "${POSTGRES_USER}",
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}",
    POSTGRES_DB: "${POSTGRES_DB}",
    POSTGRES_PORT: "${POSTGRES_PORT}",
    POSTGRES_VOLUME_NAME: "${POSTGRES_VOLUME_NAME}",
    DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}",

    HTTP_PORT: "${HTTP_PORT}",
    HTTPS_PORT: "${HTTPS_PORT}",

    DOMAIN_NAME: "${DOMAIN_NAME}",

    ADMIN_EMAIL: "${ADMIN_EMAIL}",
    ADMIN_PASSWORD: "${ADMIN_PASSWORD}",
    AUTH_SECRET: "${AUTH_SECRET}",
    AUTH_TRUST_HOST: "${AUTH_TRUST_HOST}",
    AUTH_BASE_PATH: "${AUTH_BASE_PATH}",
    AUTH_URL: "https://${DOMAIN_NAME}/auth",

    PORTFOLIO_IMAGE_NAME: "${PORTFOLIO_IMAGE_NAME}",
    APP_PORT: "${APP_PORT}",
    PORTFOLIO_HOST: "${DOMAIN_NAME}",
    PORTFOLIO_BUILD_CONTEXT: "${PORTFOLIO_BUILD_CONTEXT}",
    PORTFOLIO_WORKDIR_PATH: "${PORTFOLIO_WORKDIR_PATH}",
    PORTFOLIO_BUILD_PHASE_TARGET: "${PORTFOLIO_BUILD_PHASE_TARGET}",
    ENABLE_TLS: "${ENABLE_TLS}",
    ROUTER_ENTRYPOINT: "${ROUTER_ENTRYPOINT}",
    ACME_EMAIL: "${ADMIN_EMAIL}",
    PROMETHEUS_INTERNAL_PORT: "${PROMETHEUS_INTERNAL_PORT}",
    PROMETHEUS_EXTERNAL_PORT: "${PROMETHEUS_EXTERNAL_PORT}",
    PROMETHEUS_CONFIG_FILE_DIR: "${PROMETHEUS_CONFIG_FILE_DIR}",
    PROMETHEUS_SCRAPE_INTERVAL: "${PROMETHEUS_SCRAPE_INTERVAL}",
    PROMETHEUS_EVALUATION_INTERVAL: "${PROMETHEUS_EVALUATION_INTERVAL}",
    NODE_EXPORTER_INTERNAL_PORT: "${NODE_EXPORTER_INTERNAL_PORT}",
    NODE_EXPORTER_EXTERNAL_PORT: "${NODE_EXPORTER_EXTERNAL_PORT}",
    CADVISOR_INTERNAL_PORT: "${CADVISOR_INTERNAL_PORT}",
    CADVISOR_EXTERNAL_PORT: "${CADVISOR_EXTERNAL_PORT}",
    LOKI_INTERNAL_PORT: "${LOKI_INTERNAL_PORT}",
    LOKI_EXTERNAL_PORT: "${LOKI_EXTERNAL_PORT}",
    LOKI_CONFIG_FILE_DIR: "${LOKI_CONFIG_FILE_DIR}",
    PROMTAIL_CONFIG_FILE_DIR: "${PROMTAIL_CONFIG_FILE_DIR}",
    GRAFANA_INTERNAL_PORT: "${GRAFANA_INTERNAL_PORT}",
    GRAFANA_EXTERNAL_PORT: "${GRAFANA_EXTERNAL_PORT}",
    GRAFANA_CONFIG_DIR: "${GRAFANA_CONFIG_DIR}",
    GRAFANA_ADMIN_USER: "${GRAFANA_ADMIN_USER}",
    GRAFANA_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}",
    ALERTMANAGER_CONFIG_FILE_DIR: "${ALERTMANAGER_CONFIG_FILE_DIR}",
    ALERTMANAGER_INTERNAL_PORT: "${ALERTMANAGER_INTERNAL_PORT}",
    ALERTMANAGER_EXTERNAL_PORT: "${ALERTMANAGER_EXTERNAL_PORT}",
    ALERTMANAGER_RESOLVE_TIMEOUT: "${ALERTMANAGER_RESOLVE_TIMEOUT}",
    ALERTMANAGER_GROUP_WAIT: "${ALERTMANAGER_GROUP_WAIT}",
    ALERTMANAGER_GROUP_INTERVAL: "${ALERTMANAGER_GROUP_INTERVAL}",
    ALERTMANAGER_REPEAT_INTERVAL: "${ALERTMANAGER_REPEAT_INTERVAL}",
    ALERTMANAGER_EMAIL_TO: "${ALERTMANAGER_EMAIL_TO}",
    ALERTMANAGER_EMAIL_FROM: "${ALERTMANAGER_EMAIL_FROM}",
    ALERTMANAGER_SMTP_HOST: "${ALERTMANAGER_SMTP_HOST}",
    ALERTMANAGER_SMTP_PORT: "${ALERTMANAGER_SMTP_PORT}",
    ALERTMANAGER_SMTP_USERNAME: "${ALERTMANAGER_SMTP_USERNAME}",
    ALERTMANAGER_SMTP_PASSWORD: "${ALERTMANAGER_SMTP_PASSWORD}",
    LOKI_AUTH_ENABLED: "${LOKI_AUTH_ENABLED}",
    LOKI_GRPC_PORT: "${LOKI_GRPC_PORT}",
    LOKI_INSTANCE_ADDRESS: "${LOKI_INSTANCE_ADDRESS}",
    LOKI_PATH_PREFIX: "${LOKI_PATH_PREFIX}",
    LOKI_CHUNKS_DIR: "${LOKI_CHUNKS_DIR}",
    LOKI_RULES_DIR: "${LOKI_RULES_DIR}",
    LOKI_REPLICATION_FACTOR: "${LOKI_REPLICATION_FACTOR}",
    LOKI_KVSTORE: "${LOKI_KVSTORE}",
    PROMTAIL_HTTP_PORT: "${PROMTAIL_HTTP_PORT}",
    PROMTAIL_GRPC_PORT: "${PROMTAIL_GRPC_PORT}",
    PROMTAIL_POSITIONS_FILE: "${PROMTAIL_POSITIONS_FILE}",
    LOKI_TENANT_ID: "${LOKI_TENANT_ID}",
    LOKI_AUTH_USERNAME: "${LOKI_AUTH_USERNAME}",
    LOKI_AUTH_PASSWORD: "${LOKI_AUTH_PASSWORD}",
    ENV_TYPE: "${ENV_TYPE}",
    POSTGRES_EXPORTER_INTERNAL_PORT: "${POSTGRES_EXPORTER_INTERNAL_PORT}",
    POSTGRES_EXPORTER_EXTERNAL_PORT: "${POSTGRES_EXPORTER_EXTERNAL_PORT}",
    TRAEFIK_METRICS_PORT: "${TRAEFIK_METRICS_PORT}",
    FRONTEND_CONTAINER_NAME: "${pulumi.project}-portfolio-${pulumi.stack}",
    TRAEFIK_ALIAS: "traefik",
  }

resources: {
    appNetwork:
      {
        type: "docker:Network",
        properties: { name: "${pulumi.project}-network" },
      },

    traefikData:
      { type: "docker:Volume", properties: { name: "traefik-data" } },
    postgresDataVolume:
      {
        type: "docker:Volume",
        properties: { name: "${POSTGRES_VOLUME_NAME}" },
      },
    postgresImage:
      { type: "docker:RemoteImage", properties: { name: "postgres:17.0" } },
    postgresContainer:
      {
        type: "docker:Container",
        properties:
          {
            name: "${pulumi.project}-postgres-container-${pulumi.stack}",
            image: "${postgresImage.imageId}",
            ports:
              [{ internal: "${POSTGRES_PORT}", external: "${POSTGRES_PORT}" }],
            envs:
              [
                "POSTGRES_USER=${POSTGRES_USER}",
                "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}",
                "POSTGRES_DB=${POSTGRES_DB}",
              ],
            mounts:
              [
                {
                  type: "volume",
                  source: "${postgresDataVolume.name}",
                  target: "/var/lib/postgresql/data",
                },
              ],
            networksAdvanced:
              [{ name: "${appNetwork.name}", aliases: ["postgres"] }],
            restart: "unless-stopped",
            healthcheck:
              {
                tests: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"],
                interval: "10s",
                timeout: "5s",
                retries: 5,
              },
            wait: true,
          },
        options: { dependsOn: ["${postgresDataVolume}"] },
      },
    traefikImage:
      { type: "docker:RemoteImage", properties: { name: "traefik:v2.11" } },

    traefik:
      {
        type: "docker:Container",
        properties:
          {
            name: "${pulumi.project}-traefik-${pulumi.stack}",
            image: "${traefikImage.imageId}",
            restart: "always",
            ports:
              [
                { internal: "${HTTP_PORT}", external: "${HTTP_PORT}" },
                { internal: "${HTTPS_PORT}", external: "${HTTPS_PORT}" },
              ],
            envs: [
                "TRAEFIK_PROVIDERS_DOCKER=true",
                "TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false",
                "TRAEFIK_API_DASHBOARD=false",
                "TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:${HTTP_PORT}",
                "TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:${HTTPS_PORT}",
                "TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS=:${TRAEFIK_METRICS_PORT}",
                "TRAEFIK_METRICS_PROMETHEUS=true",
                "TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT=metrics",
                # ACME settings (used when ENABLE_TLS=true and routers set tls=true)
                "TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL=${ACME_EMAIL}",
                "TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_STORAGE=/data/acme.json",
                "TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_HTTPCHALLENGE=true",
                "TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_HTTPCHALLENGE_ENTRYPOINT=web",
              ],
            mounts:
              [
                {
                  type: "bind",
                  source: "/var/run/docker.sock",
                  target: "/var/run/docker.sock",
                  readOnly: true,
                },
                {
                  type: "volume",
                  source: "${traefikData.name}",
                  target: "/data",
                },
              ],
            networksAdvanced:
              [{ name: "${appNetwork.name}", aliases: ["${TRAEFIK_ALIAS}"] }],
          },
      },

    # Example 1: remote image for portfolio (pulls from registry)
    portfolioImage:
      {
        type: "docker:RemoteImage",
        properties:
          {
            name: "${PORTFOLIO_IMAGE_NAME}",
            build:
              {
                context: "${PORTFOLIO_BUILD_CONTEXT}",
                buildArgs:
                  { "PORTFOLIO_WORKDIR_PATH": "${PORTFOLIO_WORKDIR_PATH}" },
                target: "${PORTFOLIO_BUILD_PHASE_TARGET}",
              },
          },
      },

    portfolio:
      {
        type: "docker:Container",
        properties:
          {
            name: "${FRONTEND_CONTAINER_NAME}",
            image: "${portfolioImage.imageId}",
            restart: "always",
            envs: [
                "NODE_ENV=${NODE_ENV}",
                "DATABASE_URL=${DATABASE_URL}",
                "PORT=${APP_PORT}",
                "ADMIN_EMAIL=${ADMIN_EMAIL}",
                "ADMIN_PASSWORD=${ADMIN_PASSWORD}",
                "AUTH_SECRET=${AUTH_SECRET}",
                "AUTH_TRUST_HOST=${AUTH_TRUST_HOST}",
                "AUTH_BASE_PATH=${AUTH_BASE_PATH}",
                "AUTH_URL=${AUTH_URL}",
                # "OTEL_COLLECTOR_ENDPOINT=${OTEL_COLLECTOR_ENDPOINT}",
                # "OTEL_COLLECTOR_EXPORT_INTERVAL=${OTEL_COLLECTOR_EXPORT_INTERVAL}",
                # "OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}",
              ],
            networksAdvanced: [{ name: "${appNetwork.name}" }],
            labels:
              [
                { label: "traefik.enable", value: "true" },
                {
                  label: "traefik.http.services.portfolio.loadbalancer.server.port",
                  value: "${APP_PORT}",
                },
                {
                  label: "traefik.http.routers.portfolio.entrypoints",
                  value: "${ROUTER_ENTRYPOINT}",
                },
                {
                  label: "traefik.http.routers.portfolio.rule",
                  value: "Host(`${PORTFOLIO_HOST}`)",
                },
                {
                  label: "traefik.http.routers.portfolio.tls",
                  value: "${ENABLE_TLS}",
                },
                {
                  label: "traefik.http.routers.portfolio.tls.certresolver",
                  value: "letsencrypt",
                },
              ],
          },
        options: { dependsOn: ["${postgresContainer}"] },
      },
    observability:
      {
        type: observability:Observation,
        properties:
          {
            projectName: "${pulumi.project}",
            stackName: "${pulumi.stack}",
            prometheusInternalPort: "${PROMETHEUS_INTERNAL_PORT}",
            prometheusExternalPort: "${PROMETHEUS_EXTERNAL_PORT}",
            prometheusConfigFileDir: "${PROMETHEUS_CONFIG_FILE_DIR}",
            prometheusScrapeInterval: "${PROMETHEUS_SCRAPE_INTERVAL}",
            prometheusEvaluationInterval: "${PROMETHEUS_EVALUATION_INTERVAL}",
            nodeExporterInternalPort: "${NODE_EXPORTER_INTERNAL_PORT}",
            nodeExporterExternalPort: "${NODE_EXPORTER_EXTERNAL_PORT}",
            cadvisorInternalPort: "${CADVISOR_INTERNAL_PORT}",
            cadvisorExternalPort: "${CADVISOR_EXTERNAL_PORT}",
            lokiInternalPort: "${LOKI_INTERNAL_PORT}",
            lokiExternalPort: "${LOKI_EXTERNAL_PORT}",
            lokiConfigFileDir: "${LOKI_CONFIG_FILE_DIR}",
            promtailConfigFileDir: "${PROMTAIL_CONFIG_FILE_DIR}",
            grafanaInternalPort: "${GRAFANA_INTERNAL_PORT}",
            grafanaExternalPort: "${GRAFANA_EXTERNAL_PORT}",
            grafanaConfigDir: "${GRAFANA_CONFIG_DIR}",
            grafanaAdminUser: "${GRAFANA_ADMIN_USER}",
            grafanaAdminPassword: "${GRAFANA_ADMIN_PASSWORD}",
            domainName: "${DOMAIN_NAME}",
            alertmanagerConfigFileDir: "${ALERTMANAGER_CONFIG_FILE_DIR}",
            alertmanagerInternalPort: "${ALERTMANAGER_INTERNAL_PORT}",
            alertmanagerExternalPort: "${ALERTMANAGER_EXTERNAL_PORT}",
            alertmanagerResolveTimeout: "${ALERTMANAGER_RESOLVE_TIMEOUT}",
            alertmanagerGroupWait: "${ALERTMANAGER_GROUP_WAIT}",
            alertmanagerGroupInterval: "${ALERTMANAGER_GROUP_INTERVAL}",
            alertmanagerRepeatInterval: "${ALERTMANAGER_REPEAT_INTERVAL}",
            alertmanagerEmailTo: "${ALERTMANAGER_EMAIL_TO}",
            alertmanagerEmailFrom: "${ALERTMANAGER_EMAIL_FROM}",
            alertmanagerSmartHost: "${ALERTMANAGER_SMTP_HOST}:${ALERTMANAGER_SMTP_PORT}",
            alertmanagerSmtpUsername: "${ALERTMANAGER_SMTP_USERNAME}",
            alertmanagerSmtpPassword: "${ALERTMANAGER_SMTP_PASSWORD}",
            lokiAuthEnabled: "${LOKI_AUTH_ENABLED}",
            lokiGrpcPort: "${LOKI_GRPC_PORT}",
            lokiInstanceAddress: "${LOKI_INSTANCE_ADDRESS}",
            lokiPathPrrefix: "${LOKI_PATH_PREFIX}",
            lokiChunksDir: "${LOKI_CHUNKS_DIR}",
            lokiRulesDir: "${LOKI_RULES_DIR}",
            lokiReplicationFactor: "${LOKI_REPLICATION_FACTOR}",
            lokiKvStore: "${LOKI_KVSTORE}",
            promtailHttpPort: "${PROMTAIL_HTTP_PORT}",
            promtailGrpcPort: "${PROMTAIL_GRPC_PORT}",
            promtailPositionsFile: "${PROMTAIL_POSITIONS_FILE}",
            lokiTenantId: "${LOKI_TENANT_ID}",
            lokiAuthUsername: "${LOKI_AUTH_USERNAME}",
            lokiAuthPassword: "${LOKI_AUTH_PASSWORD}",
            envType: "${ENV_TYPE}",
            databaseUrl: "${DATABASE_URL}",
            postgresExporterInternalPort: "${POSTGRES_EXPORTER_INTERNAL_PORT}",
            postgresExporterExternalPort: "${POSTGRES_EXPORTER_EXTERNAL_PORT}",
            traefikRouterEntrypoint: "${ROUTER_ENTRYPOINT}",
            frontendNetworkAlias: "${FRONTEND_CONTAINER_NAME}",
            traefikMetricsUrl: "${TRAEFIK_ALIAS}:${TRAEFIK_METRICS_PORT}/v1/metrics",
            frontendPort: "${APP_PORT}",
          },
      },
  }
packages: { observability: "./observation" }
outputs: { portfolioHost: "${PORTFOLIO_HOST}" }
